[package]
name = "vywrs"
version = "0.2.0"
authors = ["Nurahmadie <nurahmadie@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = { version = "0.14", features = ["web_sys"] }
web-sys = "0.3"
js-sys = "0.3"
wasm-bindgen = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bytesize = "1"
anyhow = "1"
url = "2"
